Config = {}

Config.Keys = {
	["ESC"] = 322, ["F1"] = 288, ["F2"] = 289, ["F3"] = 170, ["F5"] = 166, ["F6"] = 167, ["F7"] = 168, ["F8"] = 169, ["F9"] = 56, ["F10"] = 57,
  ["~"] = 243, ["1"] = 157, ["2"] = 158, ["3"] = 160, ["4"] = 164, ["5"] = 165, ["6"] = 159, ["7"] = 161, ["8"] = 162, ["9"] = 163, ["-"] = 84, 
  ["="] = 83, ["BACKSPACE"] = 177, ["TAB"] = 37, ["Q"] = 44, ["W"] = 32, ["E"] = 38, ["R"] = 45, ["T"] = 245, ["Y"] = 246, ["U"] = 303, 
  ["P"] = 199, ["["] = 39, ["]"] = 40, ["ENTER"] = 18, ["CAPS"] = 137, ["A"] = 34, ["S"] = 8, ["D"] = 9, ["F"] = 23, ["G"] = 47, ["H"] = 74, 
  ["K"] = 311, ["L"] = 182,	["LEFTSHIFT"] = 21, ["Z"] = 20, ["X"] = 73, ["C"] = 26, ["V"] = 0, ["B"] = 29, ["N"] = 249, ["M"] = 244, [","] = 82, 
  ["."] = 81,	["LEFTCTRL"] = 36, ["LEFTALT"] = 19, ["SPACE"] = 22, ["RIGHTCTRL"] = 70, ["HOME"] = 213, ["PAGEUP"] = 10, ["PAGEDOWN"] = 11, 
  ["DELETE"] = 178,	["LEFT"] = 174, ["RIGHT"] = 175, ["TOP"] = 27, ["DOWN"] = 173,	["NENTER"] = 201, ["N4"] = 108, ["N5"] = 60, ["N6"] = 107, 
  ["N+"] = 96, ["N-"] = 97, ["N7"] = 117, ["N8"] = 61, ["N9"] = 118
}

Config.Locations = {
  ['Repair'] = {
    msg = 'Press E for Repair',
    radius = 3.0,
    props = {
      'prop_carjack',
      'prop_toolchest_05'
    }
  }
}

Config.Respray = {
  'Primary Color',
  'Secondary Color',
  'Pearlescent Color',
  'Wheel Color',
  'Tire Smoke',
}

Config.Colors = {
  ['Black'] = {
    [0]  = {name =	'Black', color = '#080808', style = 'metallic'},
    [1]  = {name =	'Graphite', color = '#0F0F0F', style = 'metallic'},
    [2]  = {name =	'Black Steel', color = '#1C1E21', style = 'metallic'},
    [3]  = {name =	'Dark Steel', color = '#292C2E', style = 'metallic'},
    [11] = {name =	'Anthracite Black', color = '#121110', style = 'metallic'},
    [12] = {name =	'Matte Black', color = '#050505', style = 'matte'},
    [15] = {name =	'Util Black', color = '#080808', style = 'metallic'},
    [16] = {name =	'Util Black Poly', color = '#121212', style = 'metallic'},
    [21] = {name =	'Worn Black', color = '#0F1012', style = 'matte'},
    [147] = {name =	'Carbon Black', color = '#080808', style = 'metallic'},
  },
  ['White'] = {
    [105] = {name =	'Sandy Brown', color = '#6E6246', style = 'metallic'},
    [107] = {name =	'Cream', color = '#CFC0A5', style = 'metallic'},
    [111] = {name =	'Ice White', color = '#F0F0F0', style = 'metallic'},
    [112] = {name =	'Frost White', color = '#B3B9C9', style = 'metallic'},
    [113] = {name =	'Worn Honey Beige', color = '#615F55', style = 'matte'},
    [121] = {name =	'Worn Off White', color = '#B0B0B0', style = 'matte'},
    [122] = {name =	'Util Off White', color = '#999999', style = 'metallic'},
    [131] = {name =	'Ice White Matte', color = '#D9D9D9', style = 'matte'},
    [132] = {name =	'Worn White', color = '#F0F0F0', style = 'matte'},
    [134] = {name =	'Pure White', color = '#FFFFFF', style = 'metallic'},
  },
  ['Grey'] = {
    [4]  = {name =	'Silver', color = '#5A5E66', style = 'metallic'},
    [5]  = {name =	'Bluish Silver', color = '#777C87', style = 'metallic'},
    [6]  = {name =	'Rolled Steel', color = '#515459', style = 'metallic'},
    [7]  = {name =	'Shadow Silver', color = '#323B47', style = 'metallic'},
    [8]  = {name =	'Stone Silver', color = '#333333', style = 'metallic'},
    [9]  = {name =	'Midnight Silver', color = '#1F2226', style = 'metallic'},
    [10] = {name =	'Cast Iron Silver', color = '#23292E', style = 'metallic'},
    [13] = {name =	'Matte Gray', color = '#121212', style = 'matte'},
    [14] = {name =	'Matte Light Gray', color = '#2F3233', style = 'matte'},
    [16] = {name =	'Util Black Poly', color = '#121212', style = 'metallic'},
    [18] = {name =	'Util Silver', color = '#575961', style = 'metallic'},
    [19] = {name =	'Util Gun Metal', color = '#23292E', style = 'metallic'},
    [20] = {name =	'Util Shadow Silver', color = '#323B47', style = 'metallic'},
    [22] = {name =	'Worn Graphite', color = '#212121', style = 'matte'},
    [23] = {name =	'Worn Silver Grey', color = '#5B5D5E', style = 'matte'},
    [24] = {name =	'Worn Silver', color = '#888A99', style = 'matte'},
    [25] = {name =	'Worn Blue Silver', color = '#697187', style = 'matte'},
    [26] = {name =	'Worn Shadow Silver', color = '#3B4654', style = 'matte'},
    [66] = {name =	'Harbor Blue', color = '#272D3B', style = 'metallic'},
    [93] = {name =	'Champagne', color = '#57514B', style = 'metallic'},
    [144] = {name =	'Hunter Green', color = '#565751', style = 'metallic'},
    [155] = {name =	'Matte Foliage Green', color = '#2B302B', style = 'matte'},
  },
  ['Red'] = {
    [27] = {name =	'Red', color = '#690000', style = 'metallic'},
    [28] = {name =	'Torino Red', color = '#8A0B00', style = 'metallic'},
    [29] = {name =	'Formula Red', color = '#6B0000', style = 'metallic'},
    [30] = {name =	'Blaze Red', color = '#611009', style = 'metallic'},
    [31] = {name =	'Grace Red', color = '#4A0A0A', style = 'metallic'},
    [32] = {name =	'Garnet Red', color = '#470E0E', style = 'metallic'},
    [33] = {name =	'Sunset Red', color = '#380C00', style = 'metallic'},
    [34] = {name =	'Cabernet Red', color = '#26030B', style = 'metallic'},
    [35] = {name =	'Candy Red', color = '#630012', style = 'metallic'},
    [39] = {name =	'Matte Red', color = '#780000', style = 'matte'},
    [40] = {name =	'Matte Dark Red', color = '#360000', style = 'matte'},
    [43] = {name =	'Util Red', color = '#520000', style = 'metallic'},
    [44] = {name =	'Util Bright Red', color = '#8C0404', style = 'metallic'},
    [45] = {name =	'Util Garnet Red', color = '#4A1000', style = 'metallic'},
    [46] = {name =	'Worn Red', color = '#592525', style = 'matte'},
    [143] = {name =	'Wine Red', color = '#080000', style = 'metallic'},
  },
  ['Pink'] = {
    [135] = {name =	'Hot Pink', color = '#B01259', style = 'metallic'},
    [136] = {name =	'Salmon Pink', color = '#F69799', style = 'metallic'},
    [137] = {name =	'Pfister Pink', color = '#8F2F55', style = 'metallic'},
  },
  ['Blue'] = {
    [54] = {name =	'Gasoline Green', color = '#0B4145', style = 'metallic'},
    [60] = {name =	'Worn Sea Wash', color = '#455C56', style = 'matte'},
    [61] = {name =	'Galaxy Blue', color = '#000D14', style = 'metallic'},
    [62] = {name =	'Dark Blue', color = '#001029', style = 'metallic'},
    [63] = {name =	'Saxon Blue', color = '#1C2F4F', style = 'metallic'},
    [64] = {name =	'Blue', color = '#001B57', style = 'metallic'},
    [65] = {name =	'Mariner Blue', color = '#3B4E78', style = 'metallic'},
    [66] = {name =	'Harbor Blue', color = '#272D3B', style = 'metallic'},
    [67] = {name =	'Diamond Blue', color = '#95B2DB', style = 'metallic'},
    [68] = {name =	'Surf Blue', color = '#3E627A', style = 'metallic'},
    [69] = {name =	'Nautical Blue', color = '#1C3140', style = 'metallic'},
    [70] = {name =	'Ultra Blue', color = '#0055C4', style = 'metallic'},
    [73] = {name =	'Racing Blue', color = '#0E316D', style = 'metallic'},
    [74] = {name =	'Light Blue', color = '#395A83', style = 'metallic'},
    [75] = {name =	'Util Dark Blue', color = '#09142E', style = 'metallic'},
    [77] = {name =	'Util Blue', color = '#152A52', style = 'metallic'},
    [78] = {name =	'Util Sea Foam Blue', color = '#324654', style = 'metallic'},
    [79] = {name =	'Util Lightning Blue', color = '#152563', style = 'metallic'},
    [80] = {name =	'Util Maui Blue Poly', color = '#223BA1', style = 'metallic'},
    [82] = {name =	'Matte Dark Blue', color = '#030E2E', style = 'matte'},
    [83] = {name =	'Matte Blue', color = '#0F1E73', style = 'matte'},
    [85] = {name =	'Worn Dark Blue', color = '#2A3754', style = 'matte'},
    [87] = {name =	'Worn Baby Blue', color = '#3B6796', style = 'matte'},
    [127] = {name =	'Police Blue', color = '#2A77A1', style = 'metallic'},
    [140] = {name =	'Fluorescent Blue', color = '#00AEEF', style = 'metallic'},
    [141] = {name =	'Midnight Blue', color = '#000108', style = 'metallic'},
    [146] = {name =	'Midnight Purple / V Dark Blue', color = '#050008', style = 'metallic'},
    [157] = {name =	'Epsilon Blue', color = '#6690B5', style = 'metallic'},
    [60] = {name =	'Worn Sea Wash', color = '#455C56', style = 'metallic'},
    [7]  = {name =	'Shadow Silver', color = '#323B47', style = 'metallic'},
  },
  ['Yellow'] = {
    [42] = {name =	'Matte Yellow', color = '#DE7E00', style = 'matte'},
    [88] = {name =	'Yellow', color = '#F5890F', style = 'metallic'},
    [89] = {name =	'Race Yellow', color = '#D9A600', style = 'metallic'},
    [91] = {name =	'Dew Yellow/Yellow Bird', color = '#A2A827', style = 'metallic'},
    [124] = {name =	'Worn Light Orange', color = '#C45C33', style = 'matte'},
  },
  ['Green'] = {
    [49] = {name =	'Dark Green', color = '#001207', style = 'metallic'},
    [50] = {name =	'Racing Green', color = '#001A0B', style = 'metallic'},
    [51] = {name =	'Sea Green', color = '#00211E', style = 'metallic'},
    [52] = {name =	'Olive Green', color = '#1F261E', style = 'metallic'},
    [53] = {name =	'Bright Green', color = '#003805', style = 'metallic'},
    [55] = {name =	'Matte Lime Green', color = '#418503', style = 'matte'},
    [56] = {name =	'Util Dark Green', color = '#0F1F15', style = 'metallic'},
    [57] = {name =	'Util Green', color = '#023613', style = 'metallic'},
    [58] = {name =	'Worn Dark Green', color = '#162419', style = 'metallic'},
    [59] = {name =	'Worn Green', color = '#2A3625', style = 'metallic'},
    [92] = {name =	'Lime Green', color = '#568F00', style = 'metallic'},
    [125] = {name =	'Pea Green/Securicor Green', color = '#47783C', style = 'metallic'},
    [128] = {name =	'Matte Green', color = '#243022', style = 'matte'},
    [133] = {name =	'Worn Olive Army Green', color = '#3F4228', style = 'metallic'},
    [151] = {name =	'Matte Forest Green', color = '#121710', style = 'matte'},
    [152] = {name =	'Matte Olive Drab', color = '#323325', style = 'matte'},
    [155] = {name =	'Matte Foliage Green', color = '#2B302B', style = 'matte'},
    [58] = {name =	'Worn Dark Green', color = '#162419', style = 'matte'},
    [59] = {name =	'Worn Green', color = '#2A3625', style = 'matte'},
  },
  ['Orange'] = {
    [36] = {name =	'Sunrise Orange', color = '#802800', style = 'metallic'},
    [38] = {name =	'Orange', color = '#BD4800', style = 'metallic'},
    [41] = {name =	'Matte Orange', color = '#AB3F00', style = 'metallic'},
    [123] = {name =	'Worn Orange', color = '#B56519', style = 'metallic'},
    [124] = {name =	'Worn Light Orange', color = '#C45C33', style = 'metallic'},
    [130] = {name =	'Worn Orange 2', color = '#C96E34', style = 'metallic'},
    [138] = {name =	'Bright Orange', color = '#C26610', style = 'metallic'},
  },
  ['Brown'] = {
    [45] = {name =	'Util Garnet Red', color = '#4A1000', style = 'metallic'},
    [47] = {name =	'Worn Golden Red', color = '#754231', style = 'matte'},
    [48] = {name =	'Worn Dark Red', color = '#210804', style = 'matte'},
    [90] = {name =	'Bronze', color = '#4A341B', style = 'metallic'},
    [94] = {name =	'Feltzer Brown', color = '#291B06', style = 'metallic'},
    [95] = {name =	'Creek Brown', color = '#262117', style = 'metallic'},
    [96] = {name =	'Chocolate Brown', color = '#120D07', style = 'metallic'},
    [97] = {name =	'Maple Brown', color = '#332111', style = 'metallic'},
    [98] = {name =	'Saddle Brown', color = '#3D3023', style = 'metallic'},
    [99] = {name =	'Straw Brown', color = '#5E5343', style = 'metallic'},
    [100] = {name =	'Moss Brown', color = '#37382B', style = 'metallic'},
    [101] = {name =	'Bison Brown', color = '#221918', style = 'metallic'},
    [102] = {name =	'WoodBeech Brown', color = '#575036', style = 'metallic'},
    [103] = {name =	'BeechWood Brown', color = '#241309', style = 'metallic'},
    [104] = {name =	'Sienna Brown', color = '#3B1700', style = 'metallic'},
    [105] = {name =	'Sandy Brown', color = '#6E6246', style = 'metallic'},
    [108] = {name =	'Util Brown', color = '#1F1709', style = 'metallic'},
    [109] = {name =	'Util Medium Brown', color = '#3D311D', style = 'metallic'},
    [114] = {name =	'Worn Brown', color = '#241E1A', style = 'matte'},
    [115] = {name =	'Worn Dark Brown', color = '#171413', style = 'matte'},
    [116] = {name =	'Worn Straw Beige', color = '#3B372F', style = 'matte'},
    [129] = {name =	'Matte Brown', color = '#6B5F54', style = 'matte'},
    [153] = {name =	'Matte Dark Earth', color = '#3B352D', style = 'matte'},
    [154] = {name =	'Matte Desert Tan', color = '#706656', style = 'matte'},
  },
  ['Purple'] = {
    [71] = {name =	'Schafter Purple', color = '#1A182E', style = 'metallic'},
    [72] = {name =	'Spinnaker Purple', color = '#161629', style = 'metallic'},
    [76] = {name =	'Util Midnight Blue', color = '#0F1021', style = 'metallic'},
    [81] = {name =	'Util Bright Blue/Slate Blue', color = '#1F1FA1', style = 'metallic'},
    [142] = {name =	'Midnight Purple', color = '#050008', style = 'metallic'},
    [145] = {name =	'Bright Purple', color = '#320642', style = 'metallic'},
    [148] = {name =	'Matte Schafter Purple', color = '#320642', style = 'matte'},
    [149] = {name =	'Matte Midnight Purple', color = '#050008', style = 'matte'},
  },
  ['Chrome'] = {
    [117] = {name =	'Brushed Steel', color = '#3B4045', style = 'chrome'},
    [118] = {name =	'Brushed Black Steel', color = '#1A1E21', style = 'chrome'},
    [119] = {name =	'Brushed Aluminium', color = '#5E646B', style = 'chrome'},
    [120] = {name =	'Chrome', color = '#000000', style = 'chrome'},
  },
  ['Gold'] = {
    [37] = {name =	'Gold', color = '#6E4F2D', style = 'metallic'},
    [158] = {name =	'Pure Gold', color = '#47391B', style = 'metallic'},
    [159] = {name =	'Brushed Gold', color = '#47391B', style = 'metallic'},
  }
}

Config.Tint = {
  [1] = "Pure Black",
	[2] = "Darksmoke",
	[3] = "Lightsmoke",
	[4] = "Limo",
  [5] = "Green"
}

Config.Horns = {
  [0]   = "Truck Horn",
  [1]   = "Cop Horn",
  [2]   = "Clown Horn",
  [3]   = "Musical Horn 1",
  [4]   = "Musical Horn 2",
  [5]   = "Musical Horn 3",
  [6]   = "Musical Horn 4",
  [7]   = "Musical Horn 5",
  [8]   = "Sad Trombone",
  [9]   = "Classical Horn 1",
  [1]   = "Classical Horn 2",
  [1]   = "Classical Horn 3",
  [1]   = "Classical Horn 4",
  [1]   = "Classical Horn 5",
  [1]   = "Classical Horn 6",
  [15]  = "Classical Horn 7",
  [16]  = "Scale - Do",
  [17]  = "Scale - Re",
  [18]  = "Scale - Mi",
  [19]  = "Scale - Fa",
  [20]  = "Scale - Sol",
  [21]  = "Scale - La",
  [22]  = "Scale - Ti",
  [23]  = "Scale - Do",
  [24]  = "Jazz Horn 1",
  [25]  = "Jazz Horn 2",
  [26]  = "Jazz Horn 3",
  [27]  = "Jazz Horn Loop",
  [28]  = "Star Spangled Banner 1",
  [29]  = "Star Spangled Banner 2",
  [30]  = "Star Spangled Banner 3",
  [31]  = "Star Spangled Banner 4",
  [32]  = "Classical Horn 8 Loop",
  [33]  = "Classical Horn 9 Loop",
  [34]  = "Classical Horn 10 Loop",
  [35]  = "Classical Horn 8",
  [36]  = "Classical Horn 9",
  [37]  = "Classical Horn 10",
  [38]  = "Funeral Loop",
  [39]  = "Funeral",
  [40]  = "Spooky Loop",
  [41]  = "Spooky",
  [42]  = "San Andreas Loop",
  [43]  = "San Andreas",
  [44]  = "Liberty City Loop",
  [45]  = "Liberty City",
  [46]  = "Festive 1 Loop",
  [47]  = "Festive 1",
  [48]  = "Festive 2 Loop",
  [49]  = "Festive 2",
  [50]  = "Festive 3 Loop",
  [51]  = "Festive 3"
}

Config.Neons = {
  ['White']         = {r = 255, 	g = 255, 	b = 255},
  ["Slate Gray"]    = {r = 112, 	g = 128, 	b = 144},
  ["Blue"]          = {r = 0, 		g = 0, 		b = 255},
  ["Light Blue"]    = {r = 0, 		g = 150, 	b = 255},
  ["Navy Blue"]     = {r = 0, 		g = 0, 		b = 128},
  ["Sky Blue"]      = {r = 135, 	g = 206, 	b = 235},
  ["Turquoise"]     = {r = 0, 		g = 245, 	b = 255},
  ["Mint Green"]    = {r = 50, 	  g = 255, 	b = 155},
  ["Lime Green"]    = {r = 0, 		g = 255, 	b = 0},
  ["Olive"]         = {r = 128, 	g = 128, 	b = 0},
  ['Yellow']        = {r = 255, 	g = 255, 	b = 0},
  ['Gold']          = {r = 255, 	g = 215, 	b = 0},
  ['Orange']        = {r = 255, 	g = 165, 	b = 0},
  ['Tan']           = {r = 245, 	g = 222, 	b = 179},
  ['Red']           = {r = 255, 	g = 0, 		b = 0},
  ['Pink']          = {r = 255, 	g = 161, 	b = 211},
  ['Bright Pink']  =	{r = 255, 	g = 0, 		b = 255},
  ['Purple']        = {r = 153, 	g = 0, 		b = 153},
  ["Ivory"]         = {r = 41, 	  g = 36, 	b = 33}
}

Config.Plates = {
  [0] = 'Blue on White 1',
	[1] = 'Yellow on Black',
	[2] = 'Yellow on Blue',
	[3] = 'Blue on White 2',
	[4] = 'Blue on White 3'
}

Config.Upgrades = {
}

Config.Mods = {
  ['Spoilers']   = { id = 0, name = 'Spoilers', tab = "body", type = "multiple"},
  ['Front Bumper']   = { id = 1, name = 'Front Bumper', tab = "body", type = "multiple"},
  ['Rear Bumper']   = { id = 2, name = 'Rear Bumper', tab = "body", type = "multiple"},
  ['Side Skirt']   = { id = 3, name = 'Side Skirt', tab = "body", type = "multiple"},
  ['Exhaust']   = { id = 4, name = 'Exhaust', tab = "body", type = "multiple"},
  ['Cage']   = { id = 5, name = 'Cage', tab = "body", type = "multiple"},
  ['Grille']   = { id = 6, name = 'Grille', tab = "body", type = "multiple"},
  ['Hood']   = { id = 7, name = 'Hood', tab = "body", type = "multiple"},
  ['Mirrors']   = { id = 8, name = 'Mirrors', tab = "body", type = "multiple"},
  ['Right Fender']   = { id = 9, name = 'Right Fender', tab = "body", type = "multiple"},
  ['Roof']  = { id = 10, name = 'Roof', tab = "body", type = "multiple"},
  ['Engine']  = { id = 11, name = 'Engine', tab = "perf", type = "multiple"},
  ['Brakes']  = { id = 12, name = 'Brakes', tab = "perf", type = "multiple"},
  ['Transmission']  = { id = 13, name = 'Transmission', tab = "perf", type = "multiple"},
  ['Horns']  = { id = 14, name = 'Horns', tab = "body", type = "multiple"},
  ['Suspension']  = { id = 15, name = 'Suspension', tab = "perf", type = "multiple"},
  ['UNK17']  = { id = 17, name = 'UNK17', tab = "", type = "toggle"},
  ['Turbo']  = { id = 18, name = 'Turbo', tab = "perf", type = "toggle"},
  ['UNK19']  = { id = 19, name = 'UNK19', tab = "", type = "toggle"},
  ['Tiresmoke']  = { id = 20, name = 'Tiresmoke', tab = "body", type = "multiple"},
  ['UNK21']  = { id = 21, name = 'UNK21', tab = "", type = "toggle"},
  ['XENON Lights']  = { id = 22, name = 'XENON Lights', tab = "body", type = "toggle"},
  ['Armor']  = { id = 16, name = 'Armor', tab = "perf", type = "multiple"},
  ['Front Wheels']  = { id = 23, name = 'Front Wheels', tab = "wheels", type = "multiple"},
  ['Back Wheels']  = { id = 24, name = 'Back Wheels', tab = "wheels", type = "multiple"},
  ['Plate Cover']  = { id = 25, name = 'Plate Cover', tab = "body", type = "multiple"},
  ['Plates']  = { id = 26, name = 'Plates', tab = "body", type = "plate"},
  ['Trim']  = { id = 27, name = 'Trim', tab = "body", type = "multiple"},
  ['Ornaments']  = { id = 28, name = 'Ornaments', tab = "body", type = "multiple"},
  ['Dashboard']  = { id = 29, name = 'Dashboard', tab = "body", type = "multiple"},
  ['Dial']  = { id = 30, name = 'Dial', tab = "body", type = "multiple"},
  ['Door Speakers']  = { id = 31, name = 'Door Speakers', tab = "body", type = "multiple"},
  ['Seats']  = { id = 32, name = 'Seats', tab = "body", type = "multiple"},
  ['Steering Wheel']  = { id = 33, name = 'Steering Wheel', tab = "body", type = "multiple"},
  ['Shifter']  = { id = 34, name = 'Shifter', tab = "body", type = "multiple"},
  ['Plaques']  = { id = 35, name = 'Plaques', tab = "body", type = "multiple"},
  ['Speakers']  = { id = 36, name = 'Speakers', tab = "body", type = "multiple"},
  ['Trunk']  = { id = 37, name = 'Trunk', tab = "body", type = "multiple"},
  ['Hydrolics']  = { id = 38, name = 'Hydrolics', tab = "body", type = "multiple"},
  ['Engines']  = { id = 39, name = 'Engine', tab = "body", type = "multiple"},
  ['Air Filter']  = { id = 40, name = 'Air Filter', tab = "body", type = "multiple"},
  ['Struts' ]  = { id = 41, name = 'Struts', tab = "body", type = "multiple"},
  ['Arch Covers']  = { id = 42, name = 'Arch Covers', tab = "body", type = "multiple"},
  ['Aerials']  = { id = 43, name = 'Aerials', tab = "body", type = "multiple"},
  ['Trim']  = { id = 44, name = 'Trim', tab = "body", type = "multiple"},
  ['Tank']  = { id = 45, name = 'Tank', tab = "body", type = "multiple"},
  ['Windows']  = { id = 46, name = 'Windows', tab = "body", type = "multiple"},
  ['UNK47']  = { id = 47, name = 'UNK47', tab = "", type = "multiple"},
  ['Livery']  = { id = 48, name = 'Livery', tab = "body", type = "multiple"},
}

Config.Wheels = {
  ['Sport'] = { id = 0},
  ['Muscle'] = { id = 1},
  ['Lowrider'] = { id = 2},
  ['SUV'] = { id = 3},
  ['All Terrain'] = { id = 4},
  ['Tuning'] = { id = 5},
  ['Motorcycle'] = { id = 6},
  ['High End'] = { id = 7},
}

